### ISSUE TITLE
Make it possible to set isstaff based on role/group name in token

### ISSUE THREAD

**Issue by ahjulstad** [Weird-Sheep-Labs/django-azure-auth#29]
It would make a great addition to be able to automatically set isstaff if the user has a specified role claim in the token, like "Contributor" or similar/configurable.

**Comment by regoawt** [comment]
Not strictly a duplicate of #23 but this will be handled in the resolution to that ticket.

**Comment by regoawt** [comment]
@ahjulstad please see https://github.com/Weird-Sheep-Labs/django-azure-auth/issues/23#issuecomment-2142771398 for an update
