### ISSUE TITLE
🐛 User attributes mapping documentation bug

### ISSUE THREAD

**Issue by mitchdawson1982** [Weird-Sheep-Labs/django-azure-auth#32]
In the user attributes mapping section of the readme, the User model example specifies an attribute `full_name` however the user mapping function example refers to `first_name`. I can raise a PR.

```
class User(AbstractUser):
    full_name = models.CharField()
```

_You want to populate the full_name field using the givenName and surname AAD user attributes i.e not a 1-to-1 mapping. You also want to mark the user as staff._

```
# main/utils.py

def user_mapping_fn(**attributes):
    return {
        "first_name": attributes["givenName"] + attributes["surname"],
        "is_staff": True,
    }
```

**Comment by regoawt** [comment]
Oh dear, thanks for noticing!

Yes feel free to raise a PR. 

Cheers

**Comment by regoawt** [comment]
No you'd need to fork the repo and open a PR that way. But I've fixed it now anyway.
